apiVersion: v1
kind: Service
metadata:
  name: toastermovie
  labels:
    app.kubernetes.io/name: toastermovie
    app.kubernetes.io/part-of: toastermovie
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: toastermovie
  ports:
    - name: http
      port: 80
      targetPort: 3000
