---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dokploy-fleet-ghcr
  namespace: toastermovie
spec:
  encryptedData:
    .dockerconfigjson: AgBOSpuO1C8z3+w3FqCTvx2DGxJ/6tenRxOYMq5mJBNdxNCNJC7QdQndFkiC+SlfzIf/yt1HDS3qYfzE/2uJ4yoic+z7Xm2Vm0w5m4eDLgqYXKdjM0uJT679DlUS1Spr3POe/HCZyF8zCtA8dJFR+WBXXaisQPWsLj4z6F+a9jLrBOmCRd3zpGZoaKCQ++P6ZEShzg92pCcC/eLswo0bhVXH5aRiMedmoGRIuajqTQVizYPYIxVj/hjmWVW9nTCKvH/9J43Fvde+HgMDj/43wH1NxhqBmedm3s8sAJxK0F/bIDbrsy5+e51GY4CztedJWc5hmo4jW4mGTfAMz8FJaHiKfevEc69B0HzUqeTeIXqxVyo0HKWB+0y2Gku3QYCLEHO71xpOIlRDhyC6F+oZH3Gcy1xIAFj6EI5McFze3ZrPZSD/NN4BXfRtxy0x8/cp+9rtGaTpWnqTEsf8fpZBU8pyApL4wDUE7Kr7//9lLZhWiNpKOpNHbDsri8kLAimwLsj8odoHqrytc05LFzR1mfZ7RXvLrjMuzIngoKBnaDnrKB4WcLmsYziSF2opMrGBj5t8//pXibCqB0jVarrEQb8/nxf9x54IoJph/wFoAi4n7RvhZn0BasJOsEczkt0KA27ryc5GrwXDrdyRbD72zUAIylITsu00x8LbAaskHJfNModP/ZQ03Xl5yvQRF63qh/hFS8muCD8wQytJ4OJtSaOebg7vRg//wgPrv3K3nQmJgWCOr8xKvNPmr+GT3sNIs4hQRXKxT5JCaDTRcGTq9Jec2OoaqGlTbXMVlsU1XS5ScjHyKKcXtpWpURLMXQVi2ranIBEgcJCIqZQqGhLScjcCSNPOAPncNpP+4kft2Nmhf9kYQK8rEBwkPCtMZdK+LnpctPt5QbpWSpxCzMiJeQ3uBKJCWj9cTt64nRRd9gskRSJZhftML3hQlCXEC49rcF7iad6b1KSpXQOA1VUeWfkoID91r6yOC+cca3mVraeOBmaZAp1lNO5bG5pIGiBpVItp2Rtqtpj9ZQD2kOLR+6uM3P979WnWx+4/ALbofwTP7wVQhK9vQGkSu7si/7fjM0MHmkEgnAva0MlrzLdF9lo4N4uddg5muykBD3QdFaJ60OAEe2HnJ2mlB/bz497h9vkQ6FXMU6DHniCz9FsrbV3MPhNMGNTjFj8g7+hZQC6nylUmav3BzpkdtPw1Re7LcBBfzkttk8YBd3dseQ==
  template:
    metadata:
      name: dokploy-fleet-ghcr
      namespace: toastermovie
    type: kubernetes.io/dockerconfigjson
