apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: toastermovie-preview
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - toastermovie.144.91.77.245.sslip.io
      secretName: toastermovie-preview-tls
  rules:
    - host: toastermovie.144.91.77.245.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: toastermovie
                port:
                  number: 80
