apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - image-pull-secret.sealedsecret.yaml
  - ingress-live.yaml
  - ingress-www-redirect.yaml
  - ingress-preview.yaml
images:
  - name: registry.144.91.77.245.sslip.io/toastermovie
    newTag: f87f731d4b8286af65c1e12dd911c19d0cdc81ea
